# Generated by Django 2.0 on 2018-09-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustonUserModel',
        ),
        migrations.AlterUniqueTogether(
            name='custonusermodel',
            unique_together={('username', 'email')},
        ),
    ]
