# Generated by Django 2.0 on 2018-10-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0002_auto_20180925_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'backup',
            },
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('n_grade', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'selected_product',
            },
        ),
        migrations.CreateModel(
            name='SubstitutProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('n_grade', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=150)),
                ('backup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.Backup')),
                ('selected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.SelectedProduct')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'substitut_product',
            },
        ),
        migrations.AddField(
            model_name='backup',
            name='selected_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.SelectedProduct'),
        ),
        migrations.AddField(
            model_name='backup',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
