# Generated by Django 2.0 on 2018-10-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_auto_20181004_1000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustonUserModel',
        ),
    ]
