# Generated by Django 2.0 on 2018-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20181006_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutproduct',
            name='img_nutrition',
            field=models.URLField(default='0000000'),
        ),
        migrations.AddField(
            model_name='substitutproduct',
            name='store',
            field=models.CharField(default='0000000', max_length=250),
        ),
        migrations.AlterField(
            model_name='substitutproduct',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='substitutproduct',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
